//! Envelope encryption for the key material.
//!
//! A passphrase derives a **key-encryption key** with Argon2id. That key wraps a **data-encryption
//! key**, which is generated by the operating system's random source and never derived from the
//! passphrase. Only the wrapped form is written down.
//!
//! The indirection is what makes rotation cheap: replacing the data key means re-wrapping a few dozen
//! bytes, not rewriting every byte of every table. Deriving the data key from the passphrase instead
//! would tie the two together and make rotation a full rewrite (ADR-002).
//!
//! Nothing here encrypts table data. That is the data path, and it is deliberately a separate piece of
//! work — see `docs/adr/ADR-002-where-encryption-sits.md`.

mod keyring;
mod secret;

pub use keyring::{Keyring, KeyringError};
