//! Envelope encryption for the key material.
//!
//! A passphrase derives a **key-encryption key** with Argon2id. That key wraps a **data-encryption
//! key**, which is generated by the operating system's random source and never derived from the
//! passphrase. Only the wrapped form is written down.
//!
//! The indirection is what makes rotation cheap: replacing the data key means re-wrapping a few dozen
//! bytes, not rewriting every byte of every table. Deriving the data key from the passphrase instead
//! would tie the two together and make rotation a full rewrite (ADR-002).
//!
//! Table data is encrypted through a **private URI scheme**, not through the format's wrapper hook.
//! That hook exists and is called, and it is not on the path a local data file takes — see
//! `docs/adr/ADR-002-where-encryption-sits.md` § Amendment for the evidence and the cost of the
//! correction. `provider` carries the scheme, `store` the sealing layer, `frame` the block framing.

mod frame;
mod keyring;
mod provider;
mod secret;
mod store;

pub(crate) use frame::{BlockFrame, BlockSize};
pub use keyring::{Keyring, KeyringError};
pub(crate) use provider::EncryptingProvider;
