//! Envelope encryption for the key material.
//!
//! A passphrase derives a **key-encryption key** with Argon2id. That key wraps a **set of
//! data-encryption keys**, each generated by the operating system's random source and never derived
//! from the passphrase. Only the wrapped form is written down.
//!
//! The indirection is what makes rotation cheap, and there are two independent kinds of it:
//!
//! - **Rotating a data key** adds a key and seals new writes under it. Everything already stored stays
//!   sealed under the key that sealed it, and that key stays in the set — every object's header names
//!   the key it was sealed with, so a rotated keyring still opens it. **No payload is rewritten.**
//! - **Changing the passphrase** re-derives the key-encryption key and re-wraps the same set. The data
//!   keys do not change, so not one stored byte does either.
//!
//! Deriving a data key from the passphrase would collapse the two and make either operation a full
//! rewrite of the database.
//!
//! Table data is encrypted through a **private URI scheme**, not through the format's wrapper hook.
//! That hook exists and is called, and it is not on the path a local data file takes — see
//! `docs/adr/ADR-002-where-encryption-sits.md` § Amendment for the evidence and the cost of the
//! correction. `provider` carries the scheme, `store` the sealing layer, `frame` the block framing.

mod capability;
mod frame;
mod keyring;
mod provider;
mod secret;
mod store;

pub(crate) use capability::Gate;
pub use capability::{Capability, Scope};
pub(crate) use frame::{BlockFrame, BlockSize};
pub use keyring::{DataKeyId, Keyring, KeyringError};
pub(crate) use provider::EncryptingProvider;
